### PR TITLE
Feature/improve mail handling

### PR DESCRIPTION
**Pull request by mluppi**

### CODE REVIEW

**Review by mgwerder — APPROVED** [review]
renaming of vars makes sense

**Review by mgwerder — APPROVED** [review]

**Review by mgwerder — APPROVED** [review]
yes...please

**Review by mgwerder — APPROVED** [review]

**Comment by mluppi** [comment]
Can the new mail configuration be tested somewhere?

**Review by mgwerder — APPROVED** [review]

**Review by mgwerder — APPROVED** [review]

**Comment by mluppi** [comment]
> Can the new mail configuration be tested somewhere?

The changes were successfully tested.

**Pull request merged**
